### ISSUE TITLE
executable c-sources not compiled into program

### ISSUE THREAD

**Issue by claudeha** [augustss/MicroCabal#9]
Reading the source code, it looks like `c-sources` for an executable would be copied to the install directory (same as for a library?) instead of being compiled into the program.

When `mcabal install` fails, I can append `-optc -I$(pwd) mycbits.c` to the failing `mhs` command and get a binary:

```
$ mcabal install
mcabal: Building executable executable-c-sources
mcabal: Build dist-mcabal/bin/mhs/executable-c-sources with mhs
/tmp/mhsc0000008372.c:10:10: fatal error: cbits.h: No such file or directory
   10 | #include "cbits.h"
      |          ^~~~~~~~~
compilation terminated.
mhs: error: command failed: cc -w -Wall -O3 -I/home/claude/.mcabal/mhs-0.11.7.1/packages/mhs-0.11.7.1/data/src/runtime   -D__MHS__  '-DVERSION_base="4.19.1.0"' '-DMIN_VERSION_base(x,y,z)=((x)<4||(x)==4&&(y)<19||(x)==4&&(y)==19&&(z)<=1)' /home/claude/.mcabal/mhs-0.11.7.1/packages/mhs-0.11.7.1/data/src/runtime/eval-unix-64.c  /tmp/mhsc0000008372.c -lm -o dist-mcabal/bin/mhs/executable-c-sources
mhs: error: callCommand: failed 256, "mhs -i -i. -idist-mcabal/autogen '-DVERSION_base=\"4.19.1.0\"' '-DMIN_VERSION_base(x,y,z)=((x)<4||(x)==4&&(y)<19||(x)==4&&(y)==19&&(z)<=1)' -a. -odist-mcabal/bin/mhs/executable-c-sources ./Main.hs"
$ mhs -i -i. -idist-mcabal/autogen '-DVERSION_base=\"4.19.1.0\"' '-DMIN_VERSION_base(x,y,z)=((x)<4||(x)==4&&(y)<19||(x)==4&&(y)==19&&(z)<=1)' -a. -odist-mcabal/bin/mhs/executable-c-sources ./Main.hs -optc -I`pwd` cbits.c 
$ ls -l dist-mcabal/bin/mhs/executable-c-sources 
-rwxr-xr-x 1 claude claude 154752 Feb 23 19:11 dist-mcabal/bin/mhs/executable-c-sources
$
```

A simple test case, which builds correctly with `cabal-3.4.1.0` `ghc-9.0.2` (Debian Bookworm) using `cabal install`:

```
==> cbits.c <==
#include "cbits.h"
void test(void)
{
}

==> cbits.h <==
#pragma once
void test(void);

==> executable-c-sources.cabal <==
cabal-version: 1.24
name: executable-c-sources
version: 0
build-type: Simple
extra-source-files: cbits.h

executable executable-c-sources
  main-is: Main.hs
  c-sources: cbits.c
  build-depends: base
  default-language: Haskell98
  other-extensions: ForeignFunctionInterface

==> Main.hs <==
{-# LANGUAGE ForeignFunctionInterface #-}

foreign import ccall "cbits.h test" test :: IO ()

main = test
```

**Comment by Rewbert** [comment]
I run into the same problem as the one described above.

**Comment by augustss** [comment]
Finally fixed in 7ef820f499acbc5c55563607029b558cf86de57c
You also need to add `include-dirs: .` to the cabal file.
